# Generated by Django 5.0.2 on 2024-04-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0003_alter_userprofile_image_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
