# Generated by Django 5.0.2 on 2024-04-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
