# Generated by Django 5.0.2 on 2024-04-13 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0005_alter_userprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User_Profile',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='image',
            new_name='profile_pic',
        ),
        migrations.AlterModelTable(
            name='user_profile',
            table=None,
        ),
    ]
