# Generated by Django 5.0.2 on 2024-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images/'),
        ),
    ]
